version: 2.1

jobs:
  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli
    working_directory: ~/build
    steps:
      - run:
          name: Install findutils
          command: |
            sudo apt-get update && sudo apt-get install -y findutils
      - run: find .
      - attach_workspace:
          at: ~/workspace
      - run: |
          export PATH=$PATH:$(pwd)/sonar-scanner-4.6.2.2472-linux/bin
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar branch value is: " $SONAR_BRANCH
          echo "Sonar org value is : " $SONAR_ORG
          sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="."
workflows:
  version: 2
  build_and_scan:
    jobs:
      - sonarqube
