  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      - run: find .
      - attach_workspace:
          at: ~/workspace
      - run: | 
          npm run start
          